### ISSUE TITLE
Computation of beta

### ISSUE THREAD

**Issue by Roumaenski** [casella/ThermoPower#20]
When trying to comprehend how beta (the variable for the beta lines) is being computed in the compressor model, i only find the variable-declaration:
Real beta(start=integer(size(tablePhic, 1)/2)) "Number of beta line";

In which way does the program determine the value of beta, which serves as an input to the three tables for Phic, Eta and PR? Some explanation in the documentation of the model would be really helpful!

**Comment by casella** [comment]
The PR vs. Phi curves of compressors are nearly horizontal near stall, and vertical in choked flow, so a direct representation of this dependency would be ill conditioned. The beta lines method adds an auxiliary variable beta, so that an implicit system is formed, that is always well defined, as long as the beta lines cross the characteristic curves with angles that are not close to 0 or 180 deg.

The beta lines method is standard in compressor modelling, see e.g. the textbook by Dixon Fluid mechanics and thermodynamics of turbomachinery, or this [answer on stack exchange](https://aviation.stackexchange.com/questions/84597/what-are-the-beta-lines-of-a-gas-turbine-engine-component).

Feel free to improve the documentation of these components according to this information and open a PR.
