### ISSUE TITLE
TestWaterFlow1DFV2ph stopped simulating in latest commit

### ISSUE THREAD

**Issue by sjoelund** [casella/ThermoPower#3]
04bcd8aafb2622cc242e205c2e69cf4949e967cf broke TestWaterFlow1DFV2ph (in the OpenModelica testsuite); non-linear system failed during initialization. I will update the OpenModelica test to use saveTotalModel to test the old behavior, but I guess you want to look into this.

**Comment by casella** [comment]
I am aware of the consequences of that fix, in general, but there are other models (not in the testsuite) that get broken because of that, and the trade-off is in favour of this commit anyway.

Commit [https://github.com/casella/ThermoPower/commit/fc86de5](https://github.com/casella/ThermoPower/commit/fc86de5f2d13d9f6faf13cbd915eda936edaea70) should fix this by restoring the original behaviour in that component.

In fact, if the back-end did its job fully, this shouldn't be necessary, but I don't have time to investigate this issue now
